version: 0.2

phases:
  pre_build:
    commands:
      - echo [INFO] LOGGING INTO AWS ECR...
      - echo [INFO] AWS VERSION
      - aws --version
      - $(aws ecr get-login --region ap-southeast-2 --no-include-email)
      - ECR_REPO_URI=051387598870.dkr.ecr.ap-southeast-2.amazonaws.com/lambda-cicd-template-test
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo [INFO] START BUILDING THE DOCKER IMAGE...
      - docker build -t $ECR_REPO_URI:latest .
      - docker tag $ECR_REPO_URI:latest $ECR_REPO_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo [INFO] DOCKER BUILD FINISHED.
      - echo [INFO] PUSHING THE DOCKER IMAGE TO ECR...
      - docker push $ECR_REPO_URI:latest
      - docker push $ECR_REPO_URI:$IMAGE_TAG
      - echo [INFO] WRITING IMAGE DEFINITION FILE...
      - printf '[{"name":"app","imageUri":"%s"}]' $ECR_REPO_URI:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json
  artifacts:
    files: imagedefinitions.json

