Transform: AWS::Serverless-2016-10-31
Description: Trigger Lambda function from API
Resourses:
  AWS: Add Debug Configuration
  MySAMLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.handler
      Runtime: python3.8
      CodeUri: ./
      MemorySize: 128
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /test
            Method: get